<a href="https://colab.research.google.com/github/Pjh940114/Study_opencv/blob/main/%5Bch_0527%5D_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
class2 = pd.read_csv("./data/class2.csv")
class2.head

<bound method NDFrame.head of    Unnamed: 0      id tissue class class2      x      y      r
0           0  CID000      C  CIRC      N  535.0  475.0  192.0
1           1  CID001      A  CIRA      N  433.0  268.0   58.0
2           2  CID002      A  CIRA      I    NaN    NaN    NaN
3           3  CID003      C  CIRC      B    NaN    NaN    NaN
4           4  CID004      F  CIRF      I  488.0  145.0   29.0
5           5  CID005      C  CIRC      B  532.0  199.0   21.0>

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
onehot_encoder = preprocessing.OneHotEncoder()

train_x = label_encoder.fit_transform(class2['class2'])
train_x

array([2, 2, 1, 0, 1, 0])

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is last chance.',
    'and if you do not have this chance.',
    'you will never get any chance.',
    'will you do get this one?',
    'please, get this chance',
]
vect = CountVectorizer()
vect.fit(corpus)
vect.vocabulary_

{'this': 13,
 'is': 7,
 'last': 8,
 'chance': 2,
 'and': 0,
 'if': 6,
 'you': 15,
 'do': 3,
 'not': 10,
 'have': 5,
 'will': 14,
 'never': 9,
 'get': 4,
 'any': 1,
 'one': 11,
 'please': 12}

In [ ]:
vect.transform(['you will never get any chance']).toarray()

array([[0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1]], dtype=int64)

In [ ]:
vect = CountVectorizer(stop_words = ['and', 'is', 'please', 'this']).fit(corpus)
vect.vocabulary_

{'last': 6,
 'chance': 1,
 'if': 5,
 'you': 11,
 'do': 2,
 'not': 8,
 'have': 4,
 'will': 10,
 'never': 7,
 'get': 3,
 'any': 0,
 'one': 9}

In [ ]:
vect.transform(['you will never get any chance']).toarray()

array([[1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1]], dtype=int64)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
doc = ['I like machine learning', 'I love deep learning', 'I run everyday']
tfidf_vectorizer = TfidfVectorizer(min_df = 1)
tfidf_matrix = tfidf_vectorizer.fit_transform(doc)
doc_distance = (tfidf_matrix * tfidf_matrix.T)
print("유사도를 위한", str(doc_distance.get_shape()[0]), 'x', str(doc_distance.get_shape()[1]), '행렬을 만들었습니다')
print(doc_distance.toarray())

유사도를 위한 3 x 3 행렬을 만들었습니다
[[1.       0.224325 0.      ]
 [0.224325 1.       0.      ]
 [0.       0.       1.      ]]


In [ ]:
print(tfidf_matrix)

  (0, 2)	0.4736296010332684
  (0, 5)	0.6227660078332259
  (0, 3)	0.6227660078332259
  (1, 0)	0.6227660078332259
  (1, 4)	0.6227660078332259
  (1, 2)	0.4736296010332684
  (2, 1)	0.7071067811865476
  (2, 6)	0.7071067811865476


In [ ]:
print(tfidf_matrix.T)

  (2, 0)	0.4736296010332684
  (5, 0)	0.6227660078332259
  (3, 0)	0.6227660078332259
  (0, 1)	0.6227660078332259
  (4, 1)	0.6227660078332259
  (2, 1)	0.4736296010332684
  (1, 2)	0.7071067811865476
  (6, 2)	0.7071067811865476


In [ ]:
print(doc_distance)

  (0, 1)	0.224324998974933
  (0, 0)	1.0000000000000002
  (1, 0)	0.224324998974933
  (1, 1)	1.0000000000000002
  (2, 2)	1.0000000000000002


In [ ]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [ ]:
from nltk.tokenize import sent_tokenize, word_tokenize
import warnings
warnings.filterwarnings(action = 'ignore')

import gensim
from gensim.models import Word2Vec

sample = open("./data/peter.txt", "r", encoding='UTF8')
s = sample.read()
f = s.replace("\n", " ")
data = []
for i in sent_tokenize(f):
    temp = []
    for j in word_tokenize(i):
        temp.append(j.lower())
    data.append(temp)
# data

In [ ]:
model1 = gensim.models.Word2Vec(data, min_count = 1,
                              vector_size = 100, window = 5)
print("Cosine similarity between 'peter' " +
                 "'wendy' - CBOW : ",
      model1.wv.similarity('peter', 'wendy'))

Cosine similarity between 'peter' 'wendy' - CBOW :  0.074393824


In [ ]:
print("Cosine similarity between 'peter' " +
                 "'hook' - CBOW : ",
      model1.wv.similarity('peter', 'hook'))

Cosine similarity between 'peter' 'hook' - CBOW :  0.02770985


In [ ]:
model2 = gensim.models.Word2Vec(data, min_count = 1, vector_size = 100,
                                             window = 5, sg = 1)
print("Cosine similarity between 'peter' " +
          "wendy' - Skip Gram : ",
    model2.wv.similarity('peter', 'wendy'))

Cosine similarity between 'peter' wendy' - Skip Gram :  0.40088683


In [ ]:
print("Cosine similarity between 'peter' " +
            "hook' - Skip Gram : ",
      model2.wv.similarity('peter', 'hook'))

Cosine similarity between 'peter' hook' - Skip Gram :  0.52016735


In [ ]:
from gensim.test.utils import common_texts
from gensim.models import FastText

model = FastText('./data/peter.txt', vector_size=4, window=3, min_count=1, epochs=10)

In [ ]:
sim_score = model.wv.similarity('peter', 'hook')
print(sim_score)

0.043825686


In [ ]:
#wiki.ko.vec 파일 내려받은 후 실습
from __future__ import print_function
from gensim.models import KeyedVectors
model_kr = KeyedVectors.load_word2vec_format('./data/wiki.ko.vec')

In [ ]:
find_similar_to = '노력'
for similar_word in model_kr.similar_by_word(find_similar_to):
    print("Word: {0}, Similarity: {1:.2f}".format(
        similar_word[0], similar_word[1]
    ))

Word: 노력함, Similarity: 0.80
Word: 노력중, Similarity: 0.75
Word: 노력만, Similarity: 0.72
Word: 노력과, Similarity: 0.71
Word: 노력의, Similarity: 0.69
Word: 노력가, Similarity: 0.69
Word: 노력이나, Similarity: 0.69
Word: 노력없이, Similarity: 0.68
Word: 노력맨, Similarity: 0.68
Word: 노력보다는, Similarity: 0.68


In [ ]:
similarities = model_kr.most_similar(positive=['동물', '육식동물'], negative=['사람'])
print(similarities)

[('초식동물', 0.7804122567176819), ('거대동물', 0.7547270655632019), ('육식동물의', 0.7547166347503662), ('유두동물', 0.753511369228363), ('반추동물', 0.7470757961273193), ('독동물', 0.7466291785240173), ('육상동물', 0.746031641960144), ('유즐동물', 0.7450903654098511), ('극피동물', 0.7449344396591187), ('복모동물', 0.742434561252594)]


In [ ]:
import numpy as np
%matplotlib notebook
import matplotlib.pyplot as plt
plt.style.use('ggplot')
from sklearn.decomposition import PCA
from gensim.test.utils import datapath, get_tmpfile
from gensim.models import KeyedVectors
from gensim.scripts.glove2word2vec import glove2word2vec

glove_file = './data/glove.6B/glove.6B.100d.txt'
word2vec_glove_file = get_tmpfile("glove.6B.100d.word2vec.txt")
glove2word2vec(glove_file, word2vec_glove_file)

(400000, 100)

In [ ]:
model = KeyedVectors.load_word2vec_format(word2vec_glove_file)
model.most_similar('bill')

[('legislation', 0.8072139620780945),
 ('proposal', 0.730686366558075),
 ('senate', 0.7142541408538818),
 ('bills', 0.704440176486969),
 ('measure', 0.6958035230636597),
 ('passed', 0.690624475479126),
 ('amendment', 0.6846879720687866),
 ('provision', 0.6845567226409912),
 ('plan', 0.6816462874412537),
 ('clinton', 0.6663140058517456)]

In [ ]:
model.most_similar('cherry')

[('peach', 0.688809871673584),
 ('mango', 0.683819055557251),
 ('plum', 0.6684104204177856),
 ('berry', 0.6590359210968018),
 ('grove', 0.658155083656311),
 ('blossom', 0.6503506302833557),
 ('raspberry', 0.6477391719818115),
 ('strawberry', 0.6442098021507263),
 ('pine', 0.6390928626060486),
 ('almond', 0.6379212737083435)]

In [ ]:
model.most_similar(negative=['cherry'])

[('kazushige', 0.48343509435653687),
 ('askerov', 0.4778185784816742),
 ('lakpa', 0.46915265917778015),
 ('ex-gay', 0.4571332633495331),
 ('tadayoshi', 0.4522107243537903),
 ('turani', 0.44810065627098083),
 ('saglam', 0.4469599425792694),
 ('aijun', 0.4435270130634308),
 ('adjustors', 0.44235292077064514),
 ('nyum', 0.4423118233680725)]

In [ ]:
result = model.most_similar(positive=['woman', 'king'], negative=['man'])
print("{}: {:.4f}".format(*result[0]))

queen: 0.7699


In [ ]:
def analogy(x1, x2, y1):
    result = model.most_similar(positive=[y1, x2], negative=[x1])
    return result[0][0]
analogy('australia', 'beer', 'france')

'champagne'

In [ ]:
analogy('tall', 'tallest', 'long')

'longest'

In [ ]:
print(model.doesnt_match("breakfast cereal dinner lunch".split())) #------ 유사도가 가장 낮은 단어를 반환

cereal
